#!/usr/bin/env python3
"""
Export Google Quick Draw test images for VHDL testbench simulation.
Generates VHDL memory initialization packages with real drawing data.
"""

import numpy as np
import os
import argparse
from pathlib import Path

def load_quickdraw_sample(training_folder="model/training_data", category=None, index=0):
    """Load a single Quick Draw sample from training data.
    
    Args:
        training_folder: Path to folder containing .npy files
        category: Category name (e.g., 'airplane', 'apple'). If None, uses first available.
        index: Which sample to use from the category (default: 0)
    
    Returns:
        tuple: (image_28x28, category_name, category_index)
    """
    # Find available categories
    npy_files = list(Path(training_folder).glob("*.npy"))
    if not npy_files:
        raise FileNotFoundError(f"No .npy files found in {training_folder}")
    
    categories = [f.stem for f in sorted(npy_files)]
    print(f"Available categories: {categories}")
    
    # Select category
    if category is None:
        category = categories[0]
        print(f"No category specified, using first: {category}")
    elif category not in categories:
        raise ValueError(f"Category '{category}' not found. Available: {categories}")
    
    category_idx = categories.index(category)
    
    # Load data
    data_path = Path(training_folder) / f"{category}.npy"
    drawings = np.load(data_path)
    
    if index >= len(drawings):
        raise IndexError(f"Index {index} out of range for category '{category}' (has {len(drawings)} samples)")
    
    # Get specific sample (already 28x28)
    image = drawings[index].reshape(28, 28).astype(np.uint8)
    
    print(f"Loaded: {category} (index {category_idx}), sample {index}")
    print(f"Image shape: {image.shape}, dtype: {image.dtype}")
    print(f"Pixel range: [{image.min()}, {image.max()}]")
    
    return image, category, category_idx


def export_vhdl_package(image, output_path="src/test_images/test_image_pkg.vhd", 
                        category="unknown", category_idx=0):
    """Export test image as a VHDL package with memory initialization.
    
    Args:
        image: 28x28 numpy array (uint8)
        output_path: Where to save the VHDL package
        category: Category name for documentation
        category_idx: Category index (for label verification)
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("-" * 80 + "\n")
        f.write("-- Google Quick Draw Test Image Package\n")
        f.write(f"-- Category: {category} (index {category_idx})\n")
        f.write(f"-- Auto-generated by export_test_image.py\n")
        f.write("-" * 80 + "\n\n")
        
        f.write("library IEEE;\n")
        f.write("use IEEE.STD_LOGIC_1164.ALL;\n")
        f.write("use IEEE.NUMERIC_STD.ALL;\n\n")
        
        f.write("package test_image_pkg is\n\n")
        
        # Image dimensions
        f.write("    constant TEST_IMAGE_SIZE : integer := 28;\n")
        f.write(f"    constant TEST_IMAGE_CATEGORY : string := \"{category}\";\n")
        f.write(f"    constant TEST_IMAGE_LABEL : integer := {category_idx};\n\n")
        
        # Image type
        f.write("    type test_image_array_t is array (0 to 27, 0 to 27) of integer range 0 to 255;\n\n")
        
        # Image data constant
        f.write("    constant TEST_IMAGE_DATA : test_image_array_t := (\n")
        for row in range(28):
            f.write("        (")
            for col in range(28):
                val = int(image[row, col])
                if col < 27:
                    f.write(f"{val:3d}, ")
                else:
                    f.write(f"{val:3d}")
            if row < 27:
                f.write("),\n")
            else:
                f.write(")\n")
        f.write("    );\n\n")
        
        f.write("end package test_image_pkg;\n\n")
        f.write("package body test_image_pkg is\n")
        f.write("end package body test_image_pkg;\n")
    
    print(f"✓ VHDL package exported to: {output_path}")


def export_npz_reference(image, category, category_idx, output_path="model/test_image_reference.npz"):
    """Export test image metadata for Python comparison scripts.
    
    Args:
        image: 28x28 numpy array (uint8)
        category: Category name
        category_idx: Category index
        output_path: Where to save the NPZ file
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    np.savez(output_path,
             image=image,
             category=category,
             category_idx=category_idx)
    
    print(f"✓ Reference NPZ saved to: {output_path}")


def export_bytes_txt(image, output_path="model/test_image_bytes.txt"):
    """Export the image as a text file with lines formatted for easy TB writes.

    Each line corresponds to one row and is written as:
      Write(8, [0x00, 0xFF, ...]);
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        for row in range(image.shape[0]):
            cols = []
            for col in range(image.shape[1]):
                val = int(image[row, col])
                cols.append(f"0x{val:02X}")
            line = "Write(8, [" + ", ".join(cols) + "]);\n"
            f.write(line)

    print(f"✓ Bytes text exported to: {output_path}")


def visualize_image(image, category):
    """Display the test image (optional, requires matplotlib)."""
    try:
        import matplotlib.pyplot as plt
        
        plt.figure(figsize=(6, 6))
        plt.imshow(image, cmap='gray', vmin=0, vmax=255)
        plt.title(f"Test Image: {category}")
        plt.axis('off')
        plt.tight_layout()
        
        output_path = "model/test_image_preview.png"
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"✓ Preview saved to: {output_path}")
        
        plt.show()
    except ImportError:
        print("ℹ️ Matplotlib not available, skipping visualization")


def load_mnist_sample(index=0, use_train=False):
    """Load a MNIST digit sample.
    
    Args:
        index: Which sample to use (default: 0)
        use_train: Use training set instead of test set (default: False)
    
    Returns:
        tuple: (image_28x28, category_name, category_index)
    """
    try:
        from tensorflow.keras.datasets import mnist
    except ImportError:
        raise ImportError("TensorFlow required for MNIST loading. Install with: pip install tensorflow")
    
    print("Loading MNIST dataset...")
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    
    # Select dataset
    if use_train:
        x_data, y_data = x_train, y_train
        dataset_name = "train"
    else:
        x_data, y_data = x_test, y_test
        dataset_name = "test"
    
    if index >= len(x_data):
        raise IndexError(f"Index {index} out of range for MNIST {dataset_name} set (has {len(x_data)} samples)")
    
    # Get specific sample
    image = x_data[index].astype(np.uint8)
    label = int(y_data[index])
    
    print(f"Loaded: MNIST digit {label} ({dataset_name} set), sample {index}")
    print(f"Image shape: {image.shape}, dtype: {image.dtype}")
    print(f"Pixel range: [{image.min()}, {image.max()}]")
    
    category = f"digit_{label}"
    
    return image, category, label


def main():
    parser = argparse.ArgumentParser(description="Export test images (Quick Draw or MNIST) for VHDL simulation")
    parser.add_argument("--source", type=str, default="quickdraw", choices=["quickdraw", "mnist"],
                    help="Data source: 'quickdraw' or 'mnist' (default: quickdraw)")
    parser.add_argument("--category", type=str, default=None,
                    help="Category name for Quick Draw (e.g., 'airplane', 'apple'). If not specified, uses first available.")
    parser.add_argument("--index", type=int, default=0,
                    help="Sample index within category (default: 0)")
    parser.add_argument("--training-folder", type=str, default="model/training_data",
                    help="Path to Quick Draw training data folder")
    parser.add_argument("--mnist-train", action="store_true",
                    help="Use MNIST training set instead of test set")
    parser.add_argument("--no-viz", action="store_true",
                    help="Skip visualization")
    
    args = parser.parse_args()
    
    print("=" * 80)
    print(f"Test Image Exporter - Source: {args.source.upper()}")
    print("=" * 80)
    
    # Load sample based on source
    if args.source == "mnist":
        image, category, category_idx = load_mnist_sample(
            index=args.index,
            use_train=args.mnist_train
        )
    else:  # quickdraw
        image, category, category_idx = load_quickdraw_sample(
            training_folder=args.training_folder,
            category=args.category,
            index=args.index
        )
    
    # Export in multiple formats
    print("\nExporting test image...")
    export_vhdl_package(image, category=category, category_idx=category_idx)
    export_npz_reference(image, category, category_idx)
    export_bytes_txt(image, output_path=f"model/test_image_bytes_{category}.txt")
    
    # Visualize
    if not args.no_viz:
        visualize_image(image, category)
    
    print("\n" + "=" * 80)
    print("✓ Export complete!")
    print("\nNext steps:")
    print("1. Include 'use work.test_image_pkg.all;' in your VHDL testbench")
    print("2. Use TEST_IMAGE_DATA(row, col) to access pixels")
    print("3. Compare results against TEST_IMAGE_LABEL")
    print("=" * 80)


if __name__ == "__main__":
    main()
